from __future__ import absolute_import

from calc.tests.base import CalcTestBase


class TestRoot(CalcTestBase):

    def test_two_root(self):
        raise Exception("Please fill me in")
